# This is a basic workflow to help you get started with Actions

name: Deepgram SDK Test

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to main
  pull_request:
    branches: [ "main" ]  # Trigger on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out your repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify your Python version

      - name: Install Deepgram SDK
        run: pip install deepgram-sdk  # Install the SDK

      - name: Run a test script
        run: |
          python -c "from deepgram import Deepgram; print('Deepgram SDK installed successfully!')"
